name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        c_compiler: [ gcc, clang ]
        include:
          - c_compiler: gcc
            cpp_compiler: g++

          - c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v2

    - name: Install Depedencies
      run: sudo apt update && sudo apt install qtbase5-dev qttools5-dev libgit2-dev googletest

    - name: Setup Build Directory
      run: mkdir build

    - name: Configure
      working-directory: build
      run: >
        cmake -D CMAKE_BUILD_TYPE=Release \
              -D CMAKE_C_COMPILER=${{ matrix.c_compiler }} \
              -D CMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
              -D INCLUDE_TESTS=ON \
              ..

    - name: Make
      working-directory: build
      run: make

    - name: Test
      working-directory: build
      run: ctest --verbose

  build-windows:

    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/mannyamorim/reef-windows-build-env:master

    steps:
    - uses: actions/checkout@v2

    - name: Setup Build Directory
      run: mkdir build

    - name: Configure
      working-directory: build
      run: x86_64-w64-mingw32.shared.posix-cmake -D CMAKE_BUILD_TYPE=Release ..

    - name: Make
      working-directory: build
      run: make

    - name: Prepare Depedencies
      working-directory: build
      run: |
        /opt/mxe/tools/copydlldeps.sh -c -d . -S "/opt/mxe/usr/x86_64-w64-mingw32.shared.posix/bin/ /opt/mxe/usr/x86_64-w64-mingw32.shared.posix/qt5/bin/" -f reef.exe
        mkdir platforms styles
        cp /opt/mxe/usr/x86_64-w64-mingw32.shared.posix/qt5/plugins/platforms/qwindows.dll ./platforms/
        cp /opt/mxe/usr/x86_64-w64-mingw32.shared.posix/qt5/plugins/styles/* ./styles/
        zip -r reef-win64.zip *.exe *.dll platforms styles

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: win64-release
        path: build/reef-win64.zip

