name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        c_compiler: [ gcc, clang ]
        include:
          - c_compiler: gcc
            cpp_compiler: g++

          - c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'false'

    - name: install deps
      run: sudo apt update && sudo apt install libncurses-dev libgit2-dev libutf8proc-dev googletest extra-cmake-modules

    - name: setup build directory
      run: mkdir build

    - name: configure
      working-directory: build
      run: cmake -D CMAKE_C_COMPILER=${{ matrix.c_compiler }} -D CMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} ..

    - name: make
      working-directory: build
      run: make

    - name: test
      working-directory: build
      run: ctest --verbose

  build-debian-src-package:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        path: reef

    - name: install deps
      run: sudo apt update && sudo apt install git-buildpackage debhelper cmake libncurses-dev libgit2-dev libutf8proc-dev googletest extra-cmake-modules

    - name: build source package
      working-directory: reef
      run: gbp buildpackage -S

    - name: archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-debian-src
        path: |
          *.build
          *.buildinfo
          *.changes
          *.dsc
          *.tar.*

  build-debian-binary-buster:

    needs: build-debian-src-package
    runs-on: ubuntu-latest
    container: debian:buster

    steps:
    - name: install deps
      run: apt update && apt install --yes git build-essential dpkg-dev debhelper cmake libncurses-dev libgit2-dev libutf8proc-dev googletest extra-cmake-modules

    - name: download source package
      uses: actions/download-artifact@v2
      with:
        name: build-debian-src

    - name: extract source package
      run: dpkg-source --extract *.dsc reef

    - name: build binary package
      working-directory: reef
      run: dpkg-buildpackage -uc -us

    - name: archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-debian-buster-amd64
        path: |
          *.build
          *.buildinfo
          *.changes
          *.deb
          *.dsc
          *.tar.*

  build-debian-binary-bullseye:

    needs: build-debian-src-package
    runs-on: ubuntu-latest
    container: debian:bullseye

    steps:
    - name: install deps
      run: apt update && apt install --yes git build-essential dpkg-dev debhelper cmake libncurses-dev libgit2-dev libutf8proc-dev googletest extra-cmake-modules

    - name: download source package
      uses: actions/download-artifact@v2
      with:
        name: build-debian-src

    - name: extract source package
      run: dpkg-source --extract *.dsc reef

    - name: build binary package
      working-directory: reef
      run: dpkg-buildpackage -uc -us

    - name: archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-debian-bullseye-amd64
        path: |
          *.build
          *.buildinfo
          *.changes
          *.deb
          *.dsc
          *.tar.*

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: setup build directory
      run: mkdir build

    - name: configure
      working-directory: build
      run: cmake ..

    - name: make
      working-directory: build
      run: cmake --build . --config Release

    - name: test
      working-directory: build
      run: ctest --verbose --build-config Release

    - name: archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-win64
        path: build\Release
