name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: install deps
      run: sudo apt install libncurses-dev libgit2-dev libutf8proc-dev

    - name: setup build directory
      run: mkdir build

    - name: configure
      working-directory: build
      run: cmake ..

    - name: make
      working-directory: build
      run: make

    - name: test
      working-directory: build
      run: ctest --verbose
